version: '3'
services:
  app:
    container_name: app
    build: 
      context: build/libs/
      dockerfile: ../../Dockerfile
      args: 
        jar_file: micrometer-log-alert-0.0.1-SNAPSHOT.jar
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./logging-alert.rules:/etc/prometheus/logging-alert.rules
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
