global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    basic_auth:
      username: 'admin'
      password: 'admin'
    metrics_path: '/prometheus'
    static_configs:
      - targets: 
        - 'app:8080' # todo Rewrite with bootJar and custome container

rule_files:
  - '/etc/prometheus/*.rules'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
          - alertmanager:9093